version: "3.2"
services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile.dev
    ports:
      - 9000:9000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile.dev
    environment:
      DEV_MODE: yes
      VECTOR_URLS: http://vector:8686
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

  vector:
    image: timberio/vector:0.37.0-debian
    volumes:
      - ./vector:/etc/vector
    command: ["--config", "/etc/vector/config.toml"]
    ports:
      - 8686:8686
