api:
  enabled: true
  address: 0.0.0.0:8686
sources:
  kubernetes_logs:
    type: kubernetes_logs
    self_node_name: "bonsoir"
    extra_label_selector: "app in (backend, vault),app.kubernetes.io/instance=koddex-poc-develop"
sinks:
  zinc:
    type: "http"
    inputs:
      - kubernetes_logs
    uri: "https://api.openobserve.ai/api/admin_organization_20704_yg9TjdWXWVB3y13/koddex/_json"
    method: "post"
    batch:
      max_bytes: 1048576  # Réduisez cette valeur si nécessaire, par exemple 524288 (512 KB)
      timeout_secs: 1
    auth:
      strategy: "basic"
      user: "infra.service@koddex.app"
      password: "89k1V2ul6X04F7p35WvM"
    compression: gzip
    encoding:
      codec: "json"
      timestamp_format: "rfc3339"
    healthcheck:
      enabled: false