[api]
address = "0.0.0.0:8686"
enabled = true

[sources.demo]
type = "demo_logs"
format = "json"
interval = 1.0

[transforms.json]
type = "remap"
inputs = ["demo"]
source = '''
. = .message
'''

[transforms.drop]
type = "filter"
inputs = ["json"]
condition = ".source == \"demo\""


[sinks.console]
type = "console"
inputs = ["drop"]
encoding.codec = "text"
